### PR TITLE
Adds colorplayground notes, snippet, documentation and screenshots

### PR DESCRIPTION
**Pull request by Evelf**
## Description of the Change

This adds a folder with sample notes to be added to one's vault:

* `theme-design-utilities-colorplay.md` and `theme-design-utilities-colorplay.css` display boxes which colors can be change with the Style Settings plugin (as showed on discord).
* `theme-design-utilities-current_theme.md` displays all the colors listed in the [cheatsheet](https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/main/cheatsheets/default-colors.pdf), but in your own vault, so it change according to your current settings.

I changed the README file to describe the content of the folder, I also described the content of the cheatsheets folder.

  ## Checklist
  - ~~[ ] Used the provided eslint configuration, [as explained in the Readme](README.md#Contribute).~~ No javascript in this PR
  - [x] Did *not* use prettier.
  - [x] Used expressive variable names.
  - [x] Code is commented well. (**I think** there's enough comments. 😅 Also, I did my best but I'm not an English native so the wording may not be the most natural for English speakers)

### CODE REVIEW

**Review by chrisgrieser — CHANGES_REQUESTED** [review]
- The css snippet can actually be added as `styles.css` – that way, the user does not have to activate any snippet, since it would already be activated as plugin css. (Also, the `styles.css` needs to be [added in the release Github Action](https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/main/.github/workflows/release.yml#L28).)
- only a minor thing, but could you only insert your new content in the README file? right now, the whole text is being replaced (which isn't a big deal, but messes up the git commit history)
- if you are proficient enough to do simple javascript, you also might wanna add a command that automatically creates new notes with the three markdown files, so the user does not have to go to github to get them. Would make the feature much more accessible for the user! (if you have little or no coding experience, then it's no big deal, to skip that feature for now)

**Comment by Evelf** [comment]
* Mmm, I didn't see the mess in the README file while checking my commit. On my computer it shows only see the part I added, so I guess it's a matter of end of line character or something like that, I'll fix that.
* I'll also remove [a line from the CSS](https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/5b41cb8809ce953a1ec84c5244e74b461e3de43c/color-playground/theme-design-utilities-colorplay.css#L122), it's overridden by the following line, I missed that while cleaning up.

I can hack some javascript like any _backend_ developer, but I don't have the setup to code and test on my computer right now.

It would be nice to have that command, and to generate a semi-random class for the color-playground note, so that the user can keep different palettes in their notes. Letting the user chose the number of boxes seems simple to code too.

I have other ideas that could fit into this theme design tools plugin or in a dedicated plugin for collecting color palettes for any usage (wardrobe, home design, ..), or re-writing the [colour lovers](https://www.colourlovers.com/lover/Eve) in obsidian maybe? :smile:

Anyway, for now:
* I'll fix this PR by cleaning the two files mentioned in the above bullet points.
* I won't add the CSS to the release Github action, nor the obsidian command, because I'm not comfortable to so without taking the time to understand what I'm actually doing.

Now that I think about it, it seems strange indeed to have useful code/ressource in this **plugin** repo that user can't access from the plugin in obsidian. Maybe it makes more sens to publish them on my [obsidian-recipes repo](https://github.com/Evelf/obsidian-recipes) and to link them from the README? But maybe it's OK to merge this as a temporary solution before one of the take the time to do the JS part?

**Comment by chrisgrieser** [comment]
> I won't add the CSS to the release Github action, nor the obsidian command, because I'm not comfortable to so without taking the time to understand what I'm actually doing.

Sure thing, I made the CSS part with [this commit here](https://github.com/chrisgrieser/obsidian-theme-design-utilities/commit/4eed5a0b8b1ddc2eec41c1384aebfc9e3b692d5d). Now you can simply copypaste the content of the `theme-design-utilities-colorplay.css` in there and it will be automatically active as soon as the user has the TDU plugin enabled. (that's what the `styles.css` file is for in a plugin repo).  (The other part was only to add it to the release action, meaning it will be included when automating releases.)

> I have other ideas that could fit into this theme design tools plugin or in a dedicated plugin for collecting color palettes for any usage (wardrobe, home design, ..), or re-writing the [colour lovers website](https://www.colourlovers.com/lover/Eve) in obsidian maybe? 😄

Sure thing, I am  definitely open for features like that :)

> I can hack some javascript like any backend developer

...and I am not even a developer (well, hobby developer maybe 😝 ). Also, there is surely some irony somewhere that a backend dev does a PR to a tool for frontend development.

As a "low-tech" solution, you could copypaste [this command for opening the cheatsheet](https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/main/main.ts#L61-L65), which does nothing more than open the cheatsheet in the browser 🙈 

You could make that command link to the `color-playground` folder on the github repo, which at least leads the user to the right place for downloading the respective markdown files?

**Comment by Evelf** [comment]
I've already fixed the README.md mess, and I'm preparing another commit to correct the unused line in the CSS.

I was looking into copying the content of the CSS into the main style.css. It almost works on my vault: the colors show up BUT the Style Setting plugin doesn't see it, so the users won't be able to customize the colors. The colors I choose are nice, but the purpose of the note is to be able to change them..

## short term plan

I go back to my initial plan, people will have to download the files and to put them in their vault manually. I'll add the command linking to the folder, but only if I'm able to make it work on my vault.

## middle-long term plan

I know the Super Charged Link plugin is able to push their CSS into the snippet folder so that people can modify it, we can copy that behavior. If I copy this behavior, I'll probably be not to far to do the same for the notes in the vault, and maybe some of the other shiny options.. :)

(also, would you add me as a friend on the discord so I can send you DM? github comments are nice to keep a log of the code design choices related to a PR, but I feel like I need to make long and serious comments, I'm a funnier person by chat)

**Comment by Evelf** [comment]
About the plugin release file, we can remove the style.css mention, but maybe we should add the images/video in the demo folder. 

The `theme-cycler.gif`is called in the README file, but the link is broken because the gif file isn't part of the release. I guess the same will happen with the 2 images I added..

**Comment by chrisgrieser** [comment]
Yeah, the Style Settings yaml requirement are slightly different for a plugin, I think 🤔 
Fixed that part. Having the stuff directly in the plugin's styles.css makes it just a bit easier in my view.

Also added the command, and since everything works released it in v.0.20 😊

**Pull request merged**
